name: HenRDP 2022

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download and install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup-latest.exe"
        Start-Process -FilePath "tailscale-setup-latest.exe" -ArgumentList "/silent" -Wait

    - name: Verify Tailscale installation
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" version

    - name: Add Tailscale AuthKey
      run: |
        $authKey = "${{ secrets.TAILSCALE_AUTHKEY }}"
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=$authKey
        Start-Sleep -Seconds 10

    - name: Enable Remote Desktop
      run: |
        $regKey = "HKLM:\System\CurrentControlSet\Control\Terminal Server"
        Set-ItemProperty -Path $regKey -Name "fDenyTSConnections" -Value 0
        $tailscaleIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        New-NetFirewallRule -Name "Allow Tailscale RDP" -Enabled True -Protocol TCP -Action Allow -LocalPort 3389 -RemoteAddress $tailscaleIP

    - name: Set Computer Name and Password
      run: |
        Rename-Computer -NewName "HenCoders-PC" -Force
        net user administrator /active:yes
        net user administrator "HenRDP2024" /add
        net localgroup administrators administrator /add

    - name: Enable Sound
      run: |
        sc config Audiosrv start= auto >nul 2>&1 || echo "Audiosrv config done"
        sc start Audiosrv >nul 2>&1 || echo "Audiosrv start done"
        sc config AudioEndpointBuilder start= auto >nul 2>&1 || echo "AudioEndpointBuilder config done"
        sc start AudioEndpointBuilder >nul 2>&1 || echo "AudioEndpointBuilder start done"

    - name: Set Tailscale to start automatically
      run: |
        Set-Service -Name "Tailscale" -StartupType Automatic
        Start-Service "Tailscale"

    - name: Restart PC to apply changes
      run: |
        Restart-Computer -Force

    - name: Wait for restart and Get Tailscale IP address
      run: |
        Start-Sleep -Seconds 30
        $tailscaleIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "Tailscale IP Address: $tailscaleIP"

    - name: Keep printing status for 30 days
      run: |
        $endTime = (Get-Date).AddDays(30)
        while ((Get-Date) -lt $endTime) {
          Write-Host "HenRdp Aktif setiap menit"
          Start-Sleep -Seconds 60
        }
