name: HenRDP 2022

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download and install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup-latest.exe"
        Start-Process -FilePath "tailscale-setup-latest.exe" -ArgumentList "/silent" -Wait
        Write-Host "Tailscale installed successfully."

    - name: Verify Tailscale installation
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" version
        Write-Host "Tailscale version checked."

    - name: Add Tailscale AuthKey
      run: |
        $authKey = "${{ secrets.TAILSCALE_AUTHKEY }}"
        Write-Host "Using Tailscale AuthKey: $authKey"
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=$authKey
        Write-Host "Tailscale auth key added successfully."

    - name: Enable Sound
      run: |
        # Mengaktifkan layanan audio
        sc config Audiosrv start= auto >nul
        sc start Audiosrv >nul
        sc config AudioEndpointBuilder start= auto >nul
        sc start AudioEndpointBuilder >nul
        Write-Host "Windows Audio service started successfully."

    - name: Enable Remote Desktop
      run: |
        # Mengaktifkan Remote Desktop
        $regKey = "HKLM:\System\CurrentControlSet\Control\Terminal Server"
        Set-ItemProperty -Path $regKey -Name "fDenyTSConnections" -Value 0

        # Membuka port RDP di Windows Firewall
        $tailscaleIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        New-NetFirewallRule -Name "Allow Tailscale RDP" -DisplayName "Allow RDP for Tailscale IP" -Enabled True -Protocol TCP -Action Allow -LocalPort 3389 -RemoteAddress $tailscaleIP
        Write-Host "RDP enabled and port 3389 opened in Windows Firewall."

    - name: Set Computer Name and Password
      run: |
        # Ubah nama PC
        Rename-Computer -NewName "HenCoders-PC" -Force
        Write-Host "PC renamed to HenCoders-PC."

        # Set username dan password untuk login RDP
        net user administrator /active:yes
        net user administrator "HenRDP2024" /add
        net localgroup administrators administrator /add
        Write-Host "Administrator account enabled and password set."

    - name: Set Tailscale to start automatically
      run: |
        Set-Service -Name "Tailscale" -StartupType Automatic
        Start-Service "Tailscale"
        Write-Host "Tailscale is set to start automatically."

    - name: Restart PC to apply changes
      run: |
        Write-Host "Restarting PC to apply changes..."
        Restart-Computer -Force

    - name: Wait for restart and Get Tailscale IP address
      run: |
        Start-Sleep -Seconds 30
        $tailscaleIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "Tailscale IP Address after restart: $tailscaleIP"

    - name: Keep printing status for 30 days
      run: |
        $endTime = (Get-Date).AddDays(30)
        while ((Get-Date) -lt $endTime) {
          Write-Host "HenRdp Aktif setiap menit"
          Start-Sleep -Seconds 60
        }
